baseURL = "https://thiyaghessan.github.io/personal-blog/"
languageCode = "en-us"
title = "Postcards from Absurdistan"
theme = "absurdistan"
paginate = 20

[taxonomies]
  tag = "tags"

[params]
  description = "Notes on things."
  author = "Thiyaghessan"